name: CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'processes/api/**'
      - 'pipeline/**'
      - 'tests/**'
      - 'pyproject.toml'
      - '.github/workflows/**'
  push:
    branches:
      - 'feature/**'
      - 'feat/**'
    paths:
      - 'processes/api/**'
      - 'pipeline/**'
      - 'tests/**'
      - 'pyproject.toml'
      - '.github/workflows/**'

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock', 'pyproject.toml') }}
          restore-keys: |
            uv-${{ runner.os }}-

      - name: Install Python 3.11 via uv
        run: uv python install 3.11

      - name: Sync dependencies (dev default)
        run: uv sync

      - name: Ruff (scoped)
        run: |
          uv run ruff check \
            pipeline/ingest/cli.py \
            processes/api \
            tests/test_api_*py \
            tests/test_runtime_validation.py

      - name: Black (scoped)
        run: |
          uv run black --check \
            pipeline/ingest/cli.py \
            processes/api \
            tests/test_api_*py \
            tests/test_runtime_validation.py

      - name: mypy (API only)
        run: uv run mypy processes/api

      - name: Pytest (full)
        run: uv run pytest -q

