name: ci
on:
  push: { branches: [ main ] }
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install uv using the official action
      - uses: astral-sh/setup-uv@v6

      - run: uv python pin 3.11 && uv sync
      - run: uv run ruff check .
      - run: uv run black --check .
      - run: uv run mypy
      - run: uv run pytest -q
