name: ci
on:
  push: { branches: [ main ] }
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/uv-action@v3
      - run: uv python pin 3.11 && uv sync
      - run: uv run ruff check .
      - run: uv run black --check .
      - run: uv run mypy
      - run: uv run pytest -q
